### ISSUE TITLE
我可以windows电脑用vlc推流，然后用开发板上的pullVideo拉流吗

### ISSUE THREAD

**Issue by tu-nie** [EZreal-zhangxing/rk_ffmpeg#12]

**Comment by EZreal-zhangxing** [comment]
可以

**Comment by tu-nie** [comment]
默认使用的是tcp，拉流时出现 method SETUP failed:461Unsupport transport
使用udp时，界面只会出现边框，过一会就结束了，请问这是什么原因

**Comment by EZreal-zhangxing** [comment]
> 默认使用的是tcp，拉流时出现 method SETUP failed:461Unsupport transport 使用udp时，界面只会出现边框，过一会就结束了，请问这是什么原因

了解下推拉流 RTSP/RTMP协议
请用基本的Debug能力去解决你碰到的问题。
