### ISSUE TITLE
npu多线程加速

### ISSUE THREAD

**Issue by zhjygit** [EZreal-zhangxing/rk_ffmpeg#13]
是否支持npu多线程加速呀。

**Comment by EZreal-zhangxing** [comment]
这个已经是使用硬件加速了。它的npu不干这个活

**Comment by zhjygit** [comment]
师傅，我的意思是，mpp是数据预处理进行硬件编解码加速，在yolo推理阶段如果使用3核npu多线程处理，能够提升推理速度。

**Comment by EZreal-zhangxing** [comment]
这个相对于软编解码有一定的加速作用。所以对编解码，推理这整个过程有一定的提升。
