### ISSUE TITLE
can not find h264_rkmpp encoder!

### ISSUE THREAD

**Issue by humorist6** [EZreal-zhangxing/rk_ffmpeg#2]
您好，我按照您说的安装好以后运行sudo ./rtsp_send_opencv_mpp -n rtmp://192.168.1.154/live/ls -hd rtmp,然后报错
[ 127 ] code:[-1] Operation not permitted. can not find h264_rkmpp encoder!
[ 668 ] code:[-1] Operation not permitted. init encoder failed!
但我发现我解码器有h264_rkmpp，但编码器没有，如何解决
解码器
/usr/local/ffmpeg/bin/ffmpeg -decoders | grep '264'
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr/local/ffmpeg --enable-version3 --enable-libdrm --enable-rkmpp --enable-libx264 --enable-nonfree --enable-gpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
 VFS..D h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 decoder wrapper (codec h264)
 V..... h264_rkmpp           h264 (rkmpp) (codec h264)
编码器：
/usr/local/ffmpeg/bin/ffmpeg -encoders | grep 'h264'
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr/local/ffmpeg --enable-version3 --enable-libdrm --enable-rkmpp --enable-libx264 --enable-nonfree --enable-gpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
 V....D libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V....D libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)

**Comment by EZreal-zhangxing** [comment]
你只是有h264编解码器，并不是h264_rkmpp的解码器，你先确保你安装了mpp以及他的测试样例能够通过，再编译安装ffmpeg。

你可以使用`-cn h264`指定使用对应的编码器

**Comment by humorist6** [comment]
您好，我的mpp测试样例都通过，但还是没有h264_rkmpp的编码器，只有解码器，没办法了



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EZreal-zhangxing/rk_ffmpeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 晚上8:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EZreal-zhangxing/rk_ffmpeg] can not find h264_rkmpp encoder! (Issue #2)





 
你只是有h264编解码器，并不是h264_rkmpp的解码器，你先确保你安装了mpp以及他的测试样例能够通过，再编译安装ffmpeg。
 
你可以使用-cn h264指定使用对应的编码器

**Comment by EZreal-zhangxing** [comment]
你看看你的ffmpeg版本是不是我指定的那个版本

**Comment by xiaotaozide** [comment]
您好！我也遇到了同样的问题，并且我的ffmpeg版本是您指定的那个版本。

**Comment by EZreal-zhangxing** [comment]
> 您好！我也遇到了同样的问题，并且我的ffmpeg版本是您指定的那个版本。

执行以下这个命令看看：`ffmpeg -encoders | grep h264`

**Comment by xiaotaozide** [comment]
您好，有h264_rkmpp编码器。
neardi@LPA3588:~/Downloads$ ffmpeg -encoders | grep h264
ffmpeg version N-107853-g6b078666d9 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
  configuration: --prefix=/usr/local/ --enable-shared --enable-version3 --enable-rkmpp --enable-libx264 --enable-gpl --enable-libdrm --enable-nonfree --enable-hwaccels --enable-gpl
  libavutil      57. 33.101 / 57. 33.101
  libavcodec     59. 42.101 / 59. 42.101
  libavformat    59. 30.100 / 59. 30.100
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 46.103 /  8. 46.103
  libswscale      6.  8.102 /  6.  8.102
  libswresample   4.  8.100 /  4.  8.100
  libpostproc    56.  7.100 / 56.  7.100
 V..... h264_rkmpp           h264 (rkmpp) (codec h264)
 V....D libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V....D libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)

**Comment by xiaotaozide** [comment]
但是报错：
[ 127 ] code:[-1] Operation not permitted. can not find h264_rkmpp encoder!
[ 668 ] code:[-1] Operation not permitted. init encoder failed!
释放回收资源：
Segmentation fault (core dumped)

**Comment by EZreal-zhangxing** [comment]
> 但是报错： [ 127 ] code:[-1] Operation not permitted. can not find h264_rkmpp encoder! [ 668 ] code:[-1] Operation not permitted. init encoder failed! 释放回收资源： Segmentation fault (core dumped)

你这个看起来是调用` avcodec_find_encoder_by_name("h264_rkmpp")` 的时候报错，
就是通过这个名字找这个编码器的时候，并没有找到。
可能原因如下：
1. 你的环境可能有多个ffmpeg。在编译的时候添加`-lavcodec` 指向了没有的ffmpeg版本
 解决方法1：检查并修改环境变量。
解决方法2：指定链接lib包的路径。

**Comment by xiaotaozide** [comment]
非常感谢您的解答，确实是有两个ffmpeg，我把没有h264_rkmpp的给删了，环境变量和lib包都是对的，还是一样的错误。
请问您知道有没有用“ffmpeg -re -i /dev/video0 -vcodec h264_rkmpp   ...   ”这种直接使用h264_rkmpp编码再进行rtsp推流的命令呀？这样我就可以试一下我的ffmpeg中的h264_rkmpp编码能不能用了。非常感谢！

**Comment by EZreal-zhangxing** [comment]
> 非常感谢您的解答，确实是有两个ffmpeg，我把没有h264_rkmpp的给删了，环境变量和lib包都是对的，还是一样的错误。 请问您知道有没有用“ffmpeg -re -i /dev/video0 -vcodec h264_rkmpp ... ”这种直接使用h264_rkmpp编码再进行rtsp推流的命令呀？这样我就可以试一下我的ffmpeg中的h264_rkmpp编码能不能用了。非常感谢！

不好意思最近有点忙，可以使用下面这个命令：
`sudo ffmpeg -re -i <input_file> -vcodec h264_rkmpp -f flv rtmp://<ip>:<port>/<url>`

你也可以在`/var/log/syslog`里面看看mpp的初始化日志有没有报错

**Comment by EZreal-zhangxing** [comment]
> 非常感谢您的解答，确实是有两个ffmpeg，我把没有h264_rkmpp的给删了，环境变量和lib包都是对的，还是一样的错误。 请问您知道有没有用“ffmpeg -re -i /dev/video0 -vcodec h264_rkmpp ... ”这种直接使用h264_rkmpp编码再进行rtsp推流的命令呀？这样我就可以试一下我的ffmpeg中的h264_rkmpp编码能不能用了。非常感谢！

如果你的输入是摄像头驱动的话需要指明捕获器
`ffmpeg -f video4linux2 -i /dev/video* ...` 这样
具体还是需要查询ffmpeg的官方文档
