### ISSUE TITLE
remote_stream关于设备驱动修改问题

### ISSUE THREAD

**Issue by gungnir33** [EZreal-zhangxing/rk_ffmpeg#4]
请问remote_stream中的设备驱动/dev/video?驱动修改是需要在源码中进行修改吗，参数中无法修改设备驱动？

**Comment by EZreal-zhangxing** [comment]
是的，目前并没有把这个值做成参数，[这行](https://github.com/EZreal-zhangxing/rk_ffmpeg/blob/08ee29bd9d1fe4b250804425f401329a16189d42/src/push_stream_with_control_keyboard_and_mouse.cpp#L559)

**Comment by gungnir33** [comment]
好的，谢谢
